version: "3"
services:
  ticket_db:
    image: mysql:5.7
    expose:
      - "3306"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=Ticket
  ticket_management:
    build:
      context: ./ticket_management_service
    deploy:
      restart_policy:
        condition: on-failure
        delay: 20s
        max_attempts: 5
        window: 10s
    restart: on-failure
    depends_on:
      - ticket_db
    links:
      - ticket_db
    ports:
      - "2300:2300"
    expose: 
      - "2300"
