version: "3.4"
services:
# ------------Support services-------------
  zookeeper:
    image: confluentinc/cp-zookeeper
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
  kafka:
    image: confluentinc/cp-kafka
    depends_on: 
      - zookeeper
    environment: 
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1

  mySQLdb:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=ThePassword
      - MYSQL_DATABASE=Day

# -------------Main services---------------

  patientmanagement:
    build: ./hall_planning_service
    links:
      - mySQLdb
    depends_on:
      - mySQLdb
    links:
      - kafka
      - zookeeper
    depends_on:
      - kafka
      - zookeeper
    ports:
      - "2223"
    expose:
      - "2223"


