version: "3.4"
services:
# ------------Support services-------------
  zookeeper:
    image: confluentinc/cp-zookeeper
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
  kafka:
    image: confluentinc/cp-kafka
    depends_on: 
      - zookeeper
    environment: 
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1

  mySQLdb:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    expose:
      - "3306:3036"
    ports:
      - "3306:3036"
    environment:
      - MYSQL_ROOT_PASSWORD=ThePassword
      - MYSQL_DATABASE=Day


# -------------Main services---------------
  hall_planning:
    build: 
      context: ./hall_planning_service
#   TODO: wait for mySQLdb
    deploy:
      restart_policy:
        condition: on-failure
        delay: 20s
        max_attempts: 5
        window: 10s
    links:
      - mySQLdb
      - kafka
      - zookeeper
    depends_on:
      - mySQLdb
      - kafka
      - zookeeper
    ports:
      - "2223"
    expose:
      - "2223"


