apiVersion: v1
kind: Pod
metadata:
  labels:
    app: api-gateway
  name: api-gateway
spec:
  containers:
  - image: api-gateway
    imagePullPolicy: Never
    name: api-gateway
    ports:
    - containerPort: 8080
    resources: {}
  restartPolicy: OnFailure
status: {}
