apiVersion: v1
kind: Pod
metadata:
  name: frontend-pod
  labels:
    environment : dev
    app: frontend
spec:
  hostname: frontend-pod
  containers:
  - image: frontend
    name: frontend-container
    imagePullPolicy: Never
    ports:
    - containerPort: 80
    resources: {}
  restartPolicy: OnFailure
status: {}