apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/mongo"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: moviedb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moviedb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: moviedb
        chaos: immune
    spec:
      containers:
      - image: mongo
        name: moviedb
        env:
          # Use secret in real usage
        - name: MONGO_INITDB_DATABASE
          value: movie
        - name: MONGODB_USERNAME
          value: root
        - name: MONGODB_PASSWORD
          value: ThePassword
        - name: MONGODB_DATABASE
          value: admin
        ports:
        - containerPort: 3306
          name: moviedb
        volumeMounts:
        - name: mongo-persistent-storage
          mountPath: /var/lib/mongo
      volumes:
      - name: mongo-persistent-storage
        persistentVolumeClaim:
          claimName: mongo-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: moviedb
spec:
  ports:
  - name: "27017"
    port: 27017
    targetPort: 27017
  clusterIP: None
  selector:
    app: moviedb
