apiVersion: v1
items:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"RoleBinding","metadata":{"annotations":{},"labels":{"origin":"github.com_Yolean_kubernetes-kafka"},"name":"kafka-pod-labler","namespace":"kafka"},"roleRef":{"apiGroup":"rbac.authorization.k8s.io","kind":"Role","name":"pod-labler"},"subjects":[{"kind":"ServiceAccount","name":"default","namespace":"kafka"}]}
    labels:
      origin: github.com_Yolean_kubernetes-kafka
    name: kafka-pod-labler
    namespace: kafka
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: pod-labler
  subjects:
  - kind: ServiceAccount
    name: default
    namespace: kafka
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
