CREATE DATABASE IF NOT EXISTS HallPlanning;
CREATE DATABASE IF NOT EXISTS Shop;
CREATE DATABASE IF NOT EXISTS Ticket;
CREATE DATABASE IF NOT EXISTS Parking;
CREATE DATABASE IF NOT EXISTS Publicity;
CREATE DATABASE IF NOT EXISTS movieflow;
select '--- Creating extra databases ---' AS '';
SET @@global.time_zone = '+00:00';
