apiVersion: v1
items:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"Role","metadata":{"annotations":{},"labels":{"origin":"github.com_Yolean_kubernetes-kafka"},"name":"pod-labler","namespace":"kafka"},"rules":[{"apiGroups":[""],"resources":["pods"],"verbs":["get","update","patch"]}]}
    labels:
      origin: github.com_Yolean_kubernetes-kafka
    name: pod-labler
    namespace: kafka
  rules:
  - apiGroups:
    - ""
    resources:
    - pods
    verbs:
    - get
    - update
    - patch
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
