apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"ClusterRole","metadata":{"annotations":{},"labels":{"origin":"github.com_Yolean_kubernetes-kafka"},"name":"node-reader"},"rules":[{"apiGroups":[""],"resources":["nodes"],"verbs":["get"]}]}
  labels:
    origin: github.com_Yolean_kubernetes-kafka
  name: node-reader
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
