apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"bootstrap","namespace":"kafka"},"spec":{"ports":[{"port":9092}],"selector":{"app":"kafka"}}}
    creationTimestamp: "2020-01-08T13:57:27Z"
    name: bootstrap
    namespace: kafka
    resourceVersion: "249708"
    selfLink: /api/v1/namespaces/kafka/services/bootstrap
    uid: a370bf84-cec9-4eee-88a9-8e551df4b1b0
  spec:
    clusterIP: 10.152.183.211
    ports:
    - port: 9092
      protocol: TCP
      targetPort: 9092
    selector:
      app: kafka
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"broker","namespace":"kafka"},"spec":{"clusterIP":"None","ports":[{"port":9092}],"selector":{"app":"kafka"}}}
    creationTimestamp: "2020-01-08T13:57:27Z"
    name: broker
    namespace: kafka
    resourceVersion: "249710"
    selfLink: /api/v1/namespaces/kafka/services/broker
    uid: 7c27f68c-7cb9-4c10-b1ed-2643f9f0a8be
  spec:
    clusterIP: None
    ports:
    - port: 9092
      protocol: TCP
      targetPort: 9092
    selector:
      app: kafka
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"pzoo","namespace":"kafka"},"spec":{"clusterIP":"None","ports":[{"name":"peer","port":2888},{"name":"leader-election","port":3888}],"selector":{"app":"zookeeper","storage":"persistent"}}}
    creationTimestamp: "2020-01-08T13:57:27Z"
    name: pzoo
    namespace: kafka
    resourceVersion: "249712"
    selfLink: /api/v1/namespaces/kafka/services/pzoo
    uid: 8c89fb36-2745-4594-8907-3106df401e96
  spec:
    clusterIP: None
    ports:
    - name: peer
      port: 2888
      protocol: TCP
      targetPort: 2888
    - name: leader-election
      port: 3888
      protocol: TCP
      targetPort: 3888
    selector:
      app: zookeeper
      storage: persistent
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"zoo","namespace":"kafka"},"spec":{"clusterIP":"None","ports":[{"name":"peer","port":2888},{"name":"leader-election","port":3888}],"selector":{"app":"zookeeper","storage":"persistent-regional"}}}
    creationTimestamp: "2020-01-08T13:57:27Z"
    name: zoo
    namespace: kafka
    resourceVersion: "249718"
    selfLink: /api/v1/namespaces/kafka/services/zoo
    uid: 7992e226-d042-4b5e-b301-5885d4acb015
  spec:
    clusterIP: None
    ports:
    - name: peer
      port: 2888
      protocol: TCP
      targetPort: 2888
    - name: leader-election
      port: 3888
      protocol: TCP
      targetPort: 3888
    selector:
      app: zookeeper
      storage: persistent-regional
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"zookeeper","namespace":"kafka"},"spec":{"ports":[{"name":"client","port":2181}],"selector":{"app":"zookeeper"}}}
    creationTimestamp: "2020-01-08T13:57:27Z"
    name: zookeeper
    namespace: kafka
    resourceVersion: "249716"
    selfLink: /api/v1/namespaces/kafka/services/zookeeper
    uid: c0c93a7e-96d4-40bc-9f66-0a20f7e23fc0
  spec:
    clusterIP: 10.152.183.198
    ports:
    - name: client
      port: 2181
      protocol: TCP
      targetPort: 2181
    selector:
      app: zookeeper
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
